name: Main Docker Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (default: latest)'
        required: false
        default: 'latest'
      environment:
        description: 'Deployment environment'
        required: false
        default: 'prod'
        

jobs:
  docker_build_push:
    uses: ./.github/workflows/reusedepoly.yml
    with:
      image_name: 'bookmymovie'
      dockerhub_username: 'shriram11'
      image_tag: ${{ github.event.inputs.image_tag || 'latest' }}
      environment: ${{ github.event.inputs.environment || 'prod' }}
      node_version: '18'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
